# -*- coding: utf-8 -*-
"""addition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ExOuOs5vSEusZ281E2uow1GN6FiPlRN8
"""

n1 = int(input("Enter the first number : "))
n2 = int(input("Enter the second number : "))

sum = n1+n2
sub = n1-n2
mul = n1*n2
print(f"The sum of {n1} and {n2} is {sum}")
print(f"The multiplication of {n1} and {n2} is {mul}")
print(f"The substraction of {n1} and {n2} is {sub}")